// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yslwztedogmbpdqppptg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlzbHd6dGVkb2dtYnBkcXBwcHRnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxMDkzMTQsImV4cCI6MjA2NTY4NTMxNH0.wSvyVc8NvSO05Z05UYsOOIs1wl-dZn8_PxZlVLxKQkg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);